import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — SubTrack AI",
  description: "Terms and conditions for using SubTrack AI.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold mb-2">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted-foreground">
              By using SubTrack AI ("the Service"), you agree to these Terms of Service. If you do not agree,
              please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">2. Service Description</h2>
            <p className="text-sm text-muted-foreground">
              SubTrack AI is a subscription tracking application that helps you monitor your subscriptions,
              detect savings opportunities using AI, and earn rewards through gamification. The Service includes:
              subscription management, AI-powered insights, price verification, deal discovery, and a rewards system.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">3. Free & Premium Plans</h2>
            <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
              <li><strong>Free Plan:</strong> Up to 3 subscriptions, basic insights, standard rewards</li>
              <li><strong>Premium Plan:</strong> Unlimited subscriptions, live price insights, advanced AI offers, priority support</li>
              <li>Premium is a recurring subscription billed monthly or annually via Stripe</li>
              <li>You can cancel your Premium subscription at any time from your profile or Stripe customer portal</li>
              <li>Refunds are handled on a case-by-case basis — contact support@scanmymenu.in</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">4. AI-Generated Content</h2>
            <p className="text-sm text-muted-foreground">
              Insights, price verifications, and savings recommendations are generated by AI and may not always
              be accurate. You should always verify pricing and terms directly with the subscription provider
              before making financial decisions. SubTrack AI is not responsible for any financial losses resulting
              from AI-generated recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">5. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1 text-sm text-muted-foreground">
              <li>You must provide accurate information when creating your account</li>
              <li>You are responsible for keeping your login credentials secure</li>
              <li>You agree not to abuse the rewards system (automated spinning, fake referrals, etc.)</li>
              <li>You agree not to scrape, reverse-engineer, or disrupt the Service</li>
              <li>You agree to comply with all applicable laws and regulations</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">6. Privacy</h2>
            <p className="text-sm text-muted-foreground">
              Your use of the Service is also governed by our{" "}
              <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.
              Please review it to understand how we handle your data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">7. Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground">
              SubTrack AI is provided "as is" without warranties of any kind. We are not liable for:
              any financial decisions made based on AI insights; loss of data due to service interruptions;
              any damages arising from the use or inability to use the Service. Our total liability shall not
              exceed the amount you've paid for Premium in the past 12 months.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">8. Account Termination</h2>
            <p className="text-sm text-muted-foreground">
              You can delete your account at any time from Profile → Delete Account. We reserve the right to
              suspend or terminate accounts that violate these Terms, abuse the rewards system, or engage in
              fraudulent activity.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">9. Changes to Terms</h2>
            <p className="text-sm text-muted-foreground">
              We may update these Terms from time to time. Continued use of the Service after changes constitutes
              acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">10. Contact</h2>
            <p className="text-sm text-muted-foreground">
              For questions about these Terms, contact: <strong>support@scanmymenu.in</strong>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <a href="/" className="text-sm text-primary hover:underline">← Back to SubTrack AI</a>
        </div>
      </div>
    </div>
  );
}
